### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by VadikAladik** [YTFort/24-Aternos#18]
Error: connect ENOENT Айпи_сервера
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'connect',
  address: 'Айпи Сервера'

бот не заходит на сервер. Версия сервера - 1 16 5

**Comment by YTFort** [comment]
Извините за игнор, вы разобрались в ошибке?
