### ISSUE TITLE
Error when running bot.js 

### ISSUE THREAD

**Issue by Litten9370** [YTFort/24-Aternos#19]
When I run bot.js it gives me this error:
![2023-02-20](https://user-images.githubusercontent.com/104330635/220215612-d11d5950-bc47-44c6-9f74-ccb834f2f387.png)

I didn't edit much, just putting in the username and port and ip for my server 
I also am just assuming the server ip goes in the host section but I don't think that has anything to do with this error

**Comment by YTFort** [comment]
did you run with node.js?
