### ISSUE TITLE
error in bot.js

### ISSUE THREAD

**Issue by RizzyFuzz** [YTFort/24-Aternos#23]
so i put my host and port and i get spammed error in console bruh

the error:

Error: connect ECONNREFUSED 185.107.194.146:23401
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '185.107.194.146',
  port: 23401

**Comment by YTFort** [comment]
Are you using python or the JS version of the bot?

If you are using JS, then the problem is in the connection, try to do something with the IP of the server or your wifi connection.

I hope it helped, if anything, please contact us!
