### ISSUE TITLE
error with main.py

### ISSUE THREAD

**Issue by Litten9370** [YTFort/24-Aternos#30]
Start
I was kicked:  {"translate":"multiplayer.disconnect.unverified_username"} (False,)
reconnect
[JSE] node:internal/process/promises:288
[JSE]             triggerUncaughtException(err, true /* fromPromise */);
[JSE]             ^
[JSE]
[JSE] [🐍  Python Error  JavaScript attempt to call 'some function' in Python failed:
[JSE] > bot.emit('kicked', packet.reason, false)
[JSE]   at Client.<anonymous> (C:\Python311\Lib\site-packages\javascript\js\node_modules\mineflayer\lib\plugins\kick.js:8:9)
[JSE]   at Client.emit (node:events:525:35)
[JSE]   at emitPacket (C:\Python311\Lib\site-packages\javascript\js\node_modules\minecraft-protocol\src\client.js:83:12)
[JSE]   at FullPacketParser.<anonymous> (C:\Python311\Lib\site-packages\javascript\js\node_modules\minecraft-protocol\src\client.js:106:9)
[JSE]   at FullPacketParser.emit (node:events:513:28)
[JSE]   at addChunk (C:\Python311\Lib\site-packages\javascript\js\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:279:12)
[JSE]   at readableAddChunk (C:\Python311\Lib\site-packages\javascript\js\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:262:11)
[JSE]
[JSE] ... across the bridge ...
[JSE]
[JSE] > bot.end(); bot.join()
[JSE]   at kicked (D:\24.Aternos.V2\Python\main.py:36)
[JSE] 🌉 TypeError: 'NoneType' object is not callable]
[JSE]
[JSE] Node.js v18.16.1

**Comment by 5ucur** [comment]
Sounds to me like the server does not allow unverified usernames - i.e. players who don't own the game. Check if toggling that option allows the bot to work normally.

**Comment by YTFort** [comment]
In order to understand what's going on, you need to know a couple of questions.
1. What OS do you have 
2. Through which program do you run the script
3. Are the necessary versions installed

**Comment by 5ucur** [comment]
I tested by disallowing cracked clients over on Aternos, and running the bot. The identical error occurred.

<details>

<summary>The error</summary>

```py
Start
I was kicked:  {"translate":"multiplayer.disconnect.unverified_username"} (False,)
reconnect
[JSE] node:internal/process/promises:289
[JSE]             triggerUncaughtException(err, true /* fromPromise */);
[JSE]             ^
[JSE] [🐍  Python Error  JavaScript attempt to call 'some function' in Python failed:
[JSE] > bot.emit('kicked', packet.reason, false)
[JSE]   at Client.<anonymous> (/home/username/Documents/Git/24-Aternos/Python/env/lib/python3.11/site-packages/javascript/js/node_modules/mineflayer/lib/plugins/kick.js:8:9)
[JSE]   at Client.emit (node:events:526:35)
[JSE]   at emitPacket (/home/username/Documents/Git/24-Aternos/Python/env/lib/python3.11/site-packages/javascript/js/node_modules/minecraft-protocol/src/client.js:83:12)
[JSE]   at FullPacketParser.<anonymous> (/home/username/Documents/Git/24-Aternos/Python/env/lib/python3.11/site-packages/javascript/js/node_modules/minecraft-protocol/src/client.js:107:9)
[JSE]   at FullPacketParser.emit (node:events:514:28)
[JSE]   at addChunk (/home/username/Documents/Git/24-Aternos/Python/env/lib/python3.11/site-packages/javascript/js/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:279:12)
[JSE]   at readableAddChunk (/home/username/Documents/Git/24-Aternos/Python/env/lib/python3.11/site-packages/javascript/js/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:262:11)
[JSE] ... across the bridge ...
[JSE] > bot.end(); bot.join()
[JSE]   at kicked (/home/username/Documents/Git/24-Aternos/Python/main.py:36)
[JSE] 🌉 TypeError: 'NoneType' object is not callable]
[JSE] Node.js v20.5.0

```

</details>


Thus, the solution should be allowing cracked clients in your Aternos server settings. It's obvious this is the reason, because the error states `multiplayer.disconnect.unverified_username` in the kick reason.

**Comment by YTFort** [comment]
Try to do this: Open server.properties and set the online-mode=false parameter
